blank_issues_enabled: false
contact_links:
    - name: 社区教程反馈表
      url: https://f.kdocs.cn/g/OUiIen4R/
      about: 如果您对 Issue 提交的流程不熟悉，也可以在此使用简单的表格进行反馈。
    - name: 社区教程交流群
      url: https://qm.qq.com/cgi-bin/qm/qr?authKey=aifKEcRSapH3pgCIIQ58qJmRs0QtiiNkeiMK3eldabfI0TJGYKje5YMgP%2FVjTFRY&k=YdLYzpkxXUwwlie6HJ1GjcnC0BgWN3es&noverify=0&group_code=749988690
      about: 提供教程中疑问、报错排错等常规问题的社区支持。(非教程库表述等内容问题请在这里寻求帮助)